common.yml
ref-manual/cvl/comments.md
ref-manual/cvl/overview.md
ref-manual/cvl/syntax.md
refman.yml

I added an overview to the syntax section, and fleshed out the syntactic conventions.  I also moved up the common elements.

CVL Overview section

---

docs/ref-manual/cli/options.md
docs/ref-manual/cvl/expr.md
docs/ref-manual/cvl/imports.md
docs/ref-manual/cvl/rules.md
docs/ref-manual/cvl/statements.md
docs/ref-manual/glossary.md
requirements.txt

Added a note to the documentation about parametric method invocations

Wrote reference manual page on rules

---

docs/user-guide/getting-started/running.md

This document was sent to me as "a small example to verify that everything is set up properly" and took me for a spin thinking my setup was indeed not proper. Should save future readers some friction.

Mention solidity version constraint

---

docs/confluence/perplexed.md

Fixing perplexed.md

---

docs/gambit/gambit.md

Updates and Fixes to Gambit Documentation

---

docs/prover/approx/hashing.md

thanks @orpistiner for pointing it out!

fix semantic error in hashing doc; also some cosmetic changes

---

.github/workflows/check.yml

Removing link check from CI, since our SSL certs are broken

removed link check

---

docs/user-guide/getting-started/install.md

The minimal Python version we support is now 3.8.16

Bump minimal Python version to 3.8.16 in install.md

---

docs/equiv-check/index.md
index.md

User documentation drafting for equiv checker
Generated: https://certora-certora-prover-documentation--99.com.readthedocs.build/en/99/docs/equiv-check/index.html

equiv check

---

docs/cvl/cvl2/changes.md

opt-out details

---

docs/cvl/cvl2/changes.md
docs/cvl/expr.md
docs/cvl/opcodes.md
docs/prover/changelog.md
docs/prover/cli/options.md
docs/user-guide/timeouts.md
spelling_wordlist.txt

cleanups and release notes

---

docs/cvl/methods.md
docs/cvl/opcodes.md
docs/prover/changelog.md
docs/prover/cli/options.md

Updates ahead of 4.8.0 - should be merged at Aug. 13

---

docs/user-guide/getting-started/install.md

Link to generated documentation: https://certora-certora-prover-documentation--136.com.readthedocs.build/en/136/docs/user-guide/getting-started/install.html

removed support for windows

---

docs/confluence/anatomy/hooks.md

fix hook pattern

---

docs/gambit/gambit.md
docs/gambit/mutation-verifier.md

Links:
- [Gambit](https://certora-certora-prover-documentation--150.com.readthedocs.build/en/150/docs/gambit/gambit.html)
- [Mutation verifier](https://certora-certora-prover-documentation--150.com.readthedocs.build/en/150/docs/gambit/mutation-verifier.html)

CERT-3448 Fix the documentation for gambit a bit

---

docs/prover/index.md
docs/prover/new_login.md
spelling_wordlist.txt

Added an instruction page for how to set up an account in cognito

added new login instructions

---

docs/cvl/methods.md

Optional example should be optional

bug fix - use optional in optional example

---

docs/prover/cli/options.md

Fix a TYPO --struct_link instead of just --link.

existing feature: Update options.md

---

docs/prover/changelog/report_changelog.md
docs/prover/new_login.md
spelling_wordlist.txt

Fixed a few spelling problems and other minor tweaks that broke the build

fixed the build

---

docs/prover/approx/hashing.md
docs/user-guide/glossary.md

this sprang from this discussion:
https://discord.com/channels/795999272293236746/1174649009697193995
Jira ticket:https://certora.atlassian.net/browse/DOC-358
Link to generated documentation: https://certora-certora-prover-documentation--175.com.readthedocs.build/en/175/

write about the constants vs hashing

---

docs/prover/techniques/index.md

Changes the navigation bar on the left, under "The Certora Prover"

[DOC-375] fixed sectioning

---

docs/prover/cli/options.md

[Generated "Options affecting summarization"](https://certora-certora-prover-documentation--186.com.readthedocs.build/en/186/docs/prover/cli/options.html#options-regarding-summarization)

[DOC-373] document optimistic_summary_recursion and summary_recursion_limit

---

docs/cvl/builtin.md

Update builtin.md for sanity rule

---

docs/cvl/expr.md

document logical operator precedence

---

docs/gambit/gambit.md

Link to generated documentation: https://certora-certora-prover-documentation--200.com.readthedocs.build/en/200/

added warning in documentation about trailing slash in remappings gambit

---

docs/prover/cli/options.md

Link to generated documentation: https://certora-certora-prover-documentation--207.com.readthedocs.build/en/207/

removed assert_contracts docs RMP-64

---

docs/user-guide/gaps.md
docs/user-guide/index.md

Jira ticket: [DOC-385](https://certora.atlassian.net/browse/DOC-385)
Link to generated documentation: https://certora-certora-prover-documentation--211.com.readthedocs.build/en/211/docs/user-guide/gaps.html
[DOC-385]: https://certora.atlassian.net/browse/DOC-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-385 Documenting peculiarities of loop unrolling

---

docs/user-guide/getting-started/install.md

Jira ticket: https://certora.atlassian.net/browse/DOC-391
Link to generated documentation: https://certora-certora-prover-documentation--212.com.readthedocs.build/en/212/docs/user-guide/getting-started/install.html

Uri/solc select DOC-391

---

docs/cvl/hooks.md
docs/cvl/statements.md

[DOC-395] Add notes on limitations of hooks

---

docs/prover/changelog/prover_changelog.md

Link to generated documentation: https://certora-certora-prover-documentation--255.com.readthedocs.build/en/255/

Uri/release notes v7.6.2

---

docs/user-guide/satisfy.md

Minor path fix in preparation for `docsinfra` changes.
- Changed a path to be relative.

Minor path fix

---

docs/prover/changelog/prover_changelog.md
spelling_wordlist.txt

added changes

---

docs/cvl/methods.md

I hope I captured the purpose of these summaries correctly, happy to change it if someone more involved with the change has something else to mention.

add ASSERT_FALSE summaries

---

docs/prover/changelog/prover_changelog.md

added changelog for 7.14.1

---

docs/prover/cli/conf-file-api.md
docs/prover/cli/options.md

CERT-7220: add documentation for solc_evm_version_map

---

docs/prover/cli/options.md
spelling_wordlist.txt

Document `contract_extensions`

---

docs/cvl/foundry-integration.md
docs/cvl/index.md
spelling_wordlist.txt

This PR adds documentation on how to use the foundry integration.

Adding Foundry Integration (Alpha Version) Readme

---

docs/user-guide/glossary.md

Feedback from https://x.com/DevDacian/status/1859114357017178333

Clarify havoc term

---

docs/prover/changelog/prover_changelog.md

Added changelog to 7.21.1 that only includes bug fixes. Also correct the number of the previous version in the changelog.

added changelog for 7.21.1

---

docs/prover/changelog/prover_changelog.md

Improving description for 7.21.1 in the changelog

better language

---

docs/prover/changelog/prover_changelog.md

Release 7.21.1 was delayed by a day; fixing the release date in the changelog to reflect that.

release 7.21.1 was delayed by a day

---

docs/solana/speclanguage.rst

CVLR Specification Language Documentation

---

docs/prover/cli/options.md
docs/solana/index.rst
docs/solana/options.md
docs/solana/output.md
docs/solana/usage.md

Just some minor nits that I found during the review.

Review of Solana docs

---

docs/cvl/expr.md

Fixing unterminated note tags
ALso, adding a title for summation so that we can directly to it from the release email.

adding a subtitle for sums

---

docs/prover/changelog/gui_changelog.md

Added GUI changelog

---

docs/prover/changelog/gui_changelog.md
docs/prover/changelog/prover_changelog.md

Added Prover changelog for 7.25.1 and corrected release date for UI changes

added changelog for 7.25.1

---

docs/prover/changelog/gui_changelog.md

GUI release notes.

---

docs/prover/cli/options.md

CERT-8524 - better description of rule patterns

---

docs/prover/changelog/gui_changelog.md

7.28.0 gui release notes

---

docs/prover/cli/index.md
docs/prover/cli/options.md

Add to the docs flags that appeared in the `--help` message that we want to keep exposed.
Link to generated documentation:

added --prover_version

---

docs/prover/cli/options.md

Adding examples for conf JSON format for CLI options.
Link to generated documentation: https://certora-certora-prover-documentation--389.com.readthedocs.build/en/389/docs/prover/cli/options.html

trying the new format for --verify

---

docs/prover/changelog/gui_changelog.md
spelling_wordlist.txt

7.29.1 Release - Added FE changelog

---

docs/ranger/how_ranger_works.md

How Ranger Works

---

docs/user-guide/patterns/safe-assum.md

Also replaced code block with code imported from the Examples repo.
Link to generated documentation: https://docs.certora.com/en/shoham-unsafe-ecrecover/docs/user-guide/patterns/safe-assum.html

Adds note regarding unsoundness of ecrecover axiom

---

docs/prover/changelog/gui_changelog.md
docs/prover/changelog/prover_changelog.md

Prover and GUI changelogs for 7.31.0

---

docs/prover/changelog/gui_changelog.md

Added Gui Changelog For 8.1.0

---

docs/cvl/methods.md

This adds a missing backtick that breaks rendering.

Add missing backtick
