Certora/Documentation

- docs/ref-manual/cvl/types.md
e.msg.address used to return the current contract's address but this is no longer the case. currentContract does this instead.
> Update available values in environment

- docs/ref-manual/cli/options.md
The --path option is passed as is to the solc compiler as the --allow-paths option.
> fix --path option

- docs/cvl/rules.md
- docs/user-guide/patterns/partial-apply.md
Prior to this commit, there were 2 instances in the documentation using the old syntax for getting a method's select (e.g. 'foo.selector()'). Now those are using the correct syntax, which does not use the function-like open + closed parentheses.
> use correct 'foo.selector' syntax in examples.

- docs/confluence/anatomy/definitions.md
prior to this commit, the type for the unquantified variable in the 'exists' example was not defined, which is not valid .spec syntax.
> fix example in old documentation's Definitions section.

- docs/gambit/index.md
- docs/gambit/mutation-verifier.md
- docs/prover/checking/mutation.md
- docs/user-guide/getting-started/install.md
This PR updates the gambit documentation to indicate that `--cloud` is now supported.
https://certora-certora-prover-documentation--61.com.readthedocs.build/en/61/docs/gambit/mutation-verifier.html
> Cloud is supported now

- docs/user-guide/getting-started/install.md
https://certora-certora-prover-documentation--66.com.readthedocs.build/en/66/docs/user-guide/getting-started/install.html
Added installation instructions for VS Code IDE extension to main prover installation instruction page.
> Added installation instructions for VS Code Certora IDE extension.

- docs/confluence/map/simple.md
Call to `contains(key)` should be cached before call to insert.
The behaviour is not incorrect since contains only changes if `succeed == true`, and `exp => true` is always true, but would be a good idea to update it for the sake of clarification.
> Fixed a semi-vacous rule in the docs

- docs/cvl/builtin.md
- docs/cvl/expr.md
- docs/prover/changelog.md
This is based on the internal changelog in confluence
Generated: https://certora-certora-prover-documentation--104.com.readthedocs.build/en/104/docs/prover/changelog.html
> Draft release notes page for CVL 2

- docs/cvl/cvl2/changes.md
- docs/cvl/expr.md
- docs/cvl/hooks.md
- docs/cvl/index.md
- docs/cvl/methods.md
- docs/cvl/overview.md
- docs/cvl/types.md
- spelling_wordlist.txt
This PR documents the restrictions on what functions can be summarized.  Since this is closely related to what types can be passed to and from solidity, I updated that as well.
In addition, since the methods block page was mostly CVL 1, I updated it to CVL 2.
Link to generated documentation:
- [type conversion](https://certora-certora-prover-documentation--114.com.readthedocs.build/en/114/docs/cvl/types.html#conversions-between-cvl-and-solidity-types)
- [expression summary restrictions](https://certora-certora-prover-documentation--114.com.readthedocs.build/en/114/docs/cvl/methods.html#function-summaries)
- [methods block page](https://certora-certora-prover-documentation--114.com.readthedocs.build/en/114/docs/cvl/methods.html#the-methods-block)
> [DOC-313] Document restrictions on summarization

- docs/cvl/expr.md
- docs/cvl/methods.md
This builds on top of #114, so that should be merged first.
Link to generated documentation: https://certora-certora-prover-documentation--115.com.readthedocs.build/en/115/docs/cvl/methods.html#function-summaries
> [DOC-314] Document the `calledContract` feature

- docs/cvl/types.md
The docs about how to reference top-level user-defined types is misleading - one must use one of the contracts in the scene, and not any contract at all. Clarify this.
> CERT-3221: clarify top-level user-defined type usage

- docs/cvl/methods.md
[Link to generated documentation](https://certora-certora-prover-documentation--132.com.readthedocs.build/en/132/docs/cvl/methods.html#function-summaries)
> small clarification for semantics of `with(env)`

- docs/cvl/expr.md
- docs/cvl/types.md
This proposal does a few things:
- allow rolling back storage state by assigning to `lastStorage` instead of using `at` syntax
- disallow calling CVL functions with `at` (this was already disallowed by the existing docs, but this documents it a little more clearly)
- add `currentStorage` as a synonym for `lastStorage`
- deprecate `at` syntax and `lastStorage` in favor of assigning to `currentStorage` and using `currentStorage` respectively.
[Additional design discussion](https://certora.atlassian.net/wiki/spaces/PROD/pages/285507607/reset+storage+syntax)
[Jira ticket](https://certora.atlassian.net/browse/CERT-1501)
Links to generated documentation:
- [types](https://certora-certora-prover-documentation--140.com.readthedocs.build/en/140/docs/cvl/types.html#the-storage-type)
- …
> [Proposal] reset storage syntax

- docs/cvl/types.md
The `storage` section in the types documentation should point to the information on storage comparison; this PR adds that.
https://certora-certora-prover-documentation--151.com.readthedocs.build/en/151/docs/cvl/types.html#the-storage-type
> added reference in types to storage comparison

- docs/prover/changelog/prover_changelog.md
- docs/prover/changelog/report_changelog.md
Previously, both the Prover release notes and the verification report release notes appears as release notes, which is ugly and less readable. Also, updated the naming of the report log to have the same convention as the prover log.
> better strings

- docs/user-guide/getting-started/install.md
I was running a basic rule to understand contract logic and recently received my premium key from the team. 
When running a job with the --debug flag, i got this:
DEBUG: https://prover.certora.com/ "POST /v2/cli/verify HTTP/1.1" 403 447
i have set up my key as an environment variable, so i was not sure what else can be the case.
It got finally solved by restarting the computer. I added a change in the documentation for everyone running into the same issue
> [CERT-3836] Update install.md

- docs/cvl/expr.md
This PR just adds a simple clarification about `.length` on dynamic arrays. Given that we also have `.length` for bytes, it is not immediately clear whether an array's length refers to the number of elements in that array, or its length in bytes.
This change reflects my current guess. Please confirm that it actually is correct!
> Explain what the length of a dynamic array is

- docs/cvl/methods.md
- docs/cvl/rules.md
Note that this PR builds on #157  and should not be merged before it is.
[Jira ticket](https://certora.atlassian.net/browse/DOC-348)
[Link to generated documentation](https://certora-certora-prover-documentation--158.com.readthedocs.build/en/158/docs/cvl/methods.html#summary-application)
> [DOC-348] Document `DELETE` summaries

- docs/cvl/v5-changes.md
- docs/prover/cli/options.md
This PR adds text to the v5 breaking changes markdown file in the mike/v5-breaking-changes branch and should be merged with that branch.  The PR contains a description of the changes, an example, a discussion of the motivation for the change, and a way to restore the previous behavior if needed.
Jira ticket: DOC-350
Link to generated documentation: [here](https://certora-certora-prover-documentation--173.com.readthedocs.build/en/173/docs/cvl/v5-changes.html)
> DOC-350: Add CERT-926 docs to the v5 changes doc set.

- docs/cvl/index.md
- docs/cvl/invariants.md
- docs/cvl/rules.md
- docs/cvl/v5-changes.md
- docs/prover/changelog/prover_changelog.md
- docs/prover/cli/options.md
[Link to generated documentation](https://certora-certora-prover-documentation--172.com.readthedocs.build/en/172/docs/cvl/v5-changes.html)
> [DOC-350] v5 change guide

- docs/cvl/cvl2/changes.md
- docs/cvl/methods.md
This moves information about `expect` clauses from the CVL 2 changes guide to the reference manual for function summaries.
[Link to generated docs](https://certora-certora-prover-documentation--176.com.readthedocs.build/en/176/docs/cvl/methods.html#function-summaries)
> migrated expect clause information to methods page

- docs/cvl/ghosts.md
- docs/user-guide/glossary.md
- Ask for help in #documentation
Jira ticket: TODO
> [DOC-367] persistent ghosts explained with examples

- docs/user-guide/getting-started/install.md
- Ask for help in #documentation
Jira ticket: https://certora.atlassian.net/browse/DOC-165
Link to generated documentation: https://certora-certora-prover-documentation--188.com.readthedocs.build/en/188/docs/user-guide/getting-started/install.html#step-2-install-the-certora-prover-package
> added link to key signup, removed mentions of the free limited version DOC-165

- docs/user-guide/timeouts/timeouts-main.md
Plan is to link from html reports' "live stats" page directly into the docs (done in this PR https://github.com/Certora/EVMVerifier/pull/4984). 
For this, I'm restructuring the timeouts-main.md page a little, so there are entry points for when each of the main statistics shows "HIGH".
Jira ticket: https://certora.atlassian.net/browse/DOC-382
Link to generated documentation: https://certora-certora-prover-documentation--198.com.readthedocs.build/en/198/docs/user-guide/timeouts/timeouts-main.html#timeout-prevention
> restructure timeouts main doc towards the main timeout statistics

- docs/prover/cli/options.md
- docs/user-guide/timeouts/timeouts-main.md
Jira tickets:
- https://certora.atlassian.net/browse/DOC-397
- https://certora.atlassian.net/browse/DOC-396
Link to generated documentation: 
https://certora-certora-prover-documentation--219.com.readthedocs.build/en/219/
> removing all references to -globalTimeout in favor of --global_timeout DOC-397 DOC-396

- docs/prover/cli/options.md
> changed optimistic_fallback description and removed the "required" true

- docs/user-guide/.htaccess
- docs/user-guide/getting-started/index.md
This is a quick patch PR to solve a broken link problem.
When googling install Certora prover, links lead to 404 page (https://docs.certora.com/en/latest/docs/user-guide/getting-started/index.html).
The page under the new structure is https://docs.certora.com/en/latest/docs/user-guide/install.html
> Redirecting old google broken link

- docs/user-guide/.htaccess
Deleting the `.htaccess` file. It didn't work as intended, and also there is an easier way to do redirections from ReadTheDocs that actually works.
> deleting now useless file

- docs/prover/changelog/report_changelog.md
This PR adds release notes for the current production version of the rule report version 2.0.1.
> Rule report relase notes for version 2.0.1

- docs/prover/cli/options.md
- The motivation for this PR is that in the new dashboard we will see the list of flags used for the run and the user will be able to click on the flag name and get to the online documentation 
- The flag and the anchor should be the same to allow a generic link creation based on flag name
These flags have help message i.e. will appear in certoraRun --help but do not have documentation in certora web documentation.
PROTOCOL_NAME
PROTOCOL_AUTHOR
BUILD_CACHE
MULTI_EXAMPLE
FUNCTION_FINDER_MODE
VYPER
SOLC_EXPERIMENTAL_VIA_IR
SOLC_MAP
STRICT_SOLC_OPTIMIZER
YUL_ABI
TYPECHECKER_ARGS
IGNORE_SOLIDITY_WARNINGS
PROVER_VERSION
BYTECODE_JSONS
> CERT-6251 - make sure all flags in documentation have a corresponding flag

- docs/prover/cli/options.md
We renamed `--structLink` to `--struct_link` some time ago, but this was still using the old one.
> CERT-6348: Fix typo, still using `--structLink`

- docs/prover/changelog/report_changelog.md
- docs/user-guide/glossary.md
In the glossary, the "call trace" entry showed "TODO". Adding an actual entry.
Link to generated documentation: https://certora-certora-prover-documentation--274.com.readthedocs.build/en/274/docs/user-guide/glossary.html#term-call-trace
> glossary entry for call trace (was: TODO)

- docs/prover/cli/options.md
The anchors to the flag documentation do not work correctly for example `https://docs.certora.com/en/latest/docs/prover/cli/options.html#method`
goes to the table of content not to the paragraph itself. 
Fix by the following:
- using only the (XXX)= format
- underscores are not supported in anchors (changed automatically to dashes) 
- anchors should be in lowercase - toggled case when needed
> CERT-6671 - fix anchors

- _requirements.txt
- requirements.txt
- The `certifi` package needed to be upgraded to >= 2024.7.4. See:
-  https://github.com/Certora/docs-infrastructure/security/dependabot/5
- This required updating the `sphinx` package to version 7.4.5.
- Other packages has been updated.
- Also using the `shoham/upgrade-packages` branch of `docsinfra` package to prevent conflicting requirements. This will be changed back to `master` once the branch has been merged.
*Build:* https://docs.certora.com/en/shoham-upgrade-certifi/
> Upgrades packages due to update in `certifi`

- docs/prover/approx/grounding.md
Add missing == 0 in rewritten example about quantified variables as arguments
> Small fix in example

- docs/cvl/methods.md
> remove merge indicators

- docs/cvl/types.md
since the user-defined types are not inherited, so the `Child.ParentFileType` is not valid. instead, we should use `Child.ChildFileType`
[link](https://docs.certora.com/en/latest/docs/cvl/types.html#id5)
> Update types.md, using the wrong type

- docs/user-guide/glossary.md
- spelling_wordlist.txt
Based on changes in https://github.com/Certora/EVMVerifier/pull/6226 for the display of that.
- Add link to generated documentation …
> CERT-6637: Add entry about receiveOrFallback in glossary

- docs/cvl/methods.md
> document new unresolved call syntax

- docs/cvl/expr.md
> Document address function calls

- docs/cvl/expr.md
Reverts Certora/Documentation#292
We're not announcing this feature yet.
> Revert "Document address function calls"

- docs/prover/changelog/prover_changelog.md
* Adding Rule Report release notes to the main release notes
* A minor typo - CVL was listed as first bullet in the release notes.
> Adding Rule Report changes to the release notes

- docs/cvl/statements.md
Removed old syntax(`invoke_fallback`, `invoke_whole`, and `call`) from the [documentation](https://docs.certora.com/en/latest/docs/cvl/statements.html#syntax) as proposed on [Discord](https://discord.com/channels/795999272293236746/1283926719597908091).
> invoke_ syntax removed from the doc

- docs/cvl/cvl2/changes.md
- docs/cvl/expr.md
- docs/cvl/ghosts.md
- docs/cvl/methods.md
- docs/cvl/types.md
- docs/prover/changelog/prover_changelog.md
A very minimal way to not lie about the fact that we can have arbitrary expressions and not just function calls in the summaries. Multiple people seemed recently confused about that.
We could probably write more about it, but if the most prominent usecase still is to just call a function, I'm not sure we have to.
> General expression summaries

- docs/cvl/methods.md
There was a merge conflict [introduced in this PR](https://github.com/Certora/Documentation/pull/291) that made it to the documentation [on this page](https://docs.certora.com/en/latest/docs/cvl/methods.html). This PR resolves the merge.
> Resolve merge conflict in methods.md

- docs/sunbeam/index.rst
- docs/sunbeam/installation.rst
- docs/sunbeam/troubleshooting.rst
- docs/user-guide/install.md
- index.rst
Adds:
- Installation instructions
- Troubleshooting
Link to generated documentation: https://docs.certora.com/en/shoham-sunbeam-init/index.html
The new section: https://docs.certora.com/en/shoham-sunbeam-init/docs/sunbeam/index.html
> Docs for sunbeam

- docs/gambit/mutation-verifier.md
**There is a typo in this doc:**
In the section "Randomly generated mutations via Gambit," the sentence:
> To **generated** random mutations via {doc}`Gambit <gambit>`, 
Should be:
> To **generate** random mutations via {doc}`Gambit <gambit>`, 
The word "generated" replaced with "**generate**," as it should be in the infinitive form following "To."
I’m practically a fan of Certora at this point! I admire how they’ve structured their documentation and tools, but even the best of us can slip up occasionally 😄
> Typo Update mutation-verifier.md

- docs/prover/changelog/report_changelog.md
This PR adds the release notes for the rule report version 3.0.1
> Rule Report Release notes for Version 3.0.1

- docs/prover/changelog/prover_changelog.md
Link to generated documentation: https://certora-certora-prover-documentation--316.com.readthedocs.build/en/316/
> added changelog for 7.20.1

- docs/cvl/cvl2/changes.md
We had some discussions about what the semantics of the CVL modulo should be. The result is to keep the currently *implemented* semantics, which is different from what our documentation says.
> CERT-7605: Fix documentation about CVL modulo

- docs/cvl/methods.md
Clarify that the unresolved calls entry only applies in cases where the function's sighash is unresolved.
*Note.* this also updates the _Examples_ sub-module.
Link to generated documentation: https://docs.certora.com/en/shoham-clarify-unresolved/docs/cvl/methods.html#catch-unresolved-calls-entry
> Carify unresolved calls entry

- docs/prover/changelog/gui_changelog.md
- docs/prover/changelog/index.md
- docs/prover/changelog/prover_changelog.md
- spelling_wordlist.txt
- Added log for the new FE version
- Renamed the rule report changelog to GUI changelog, to reflect that it also includes dashboard changes
Link to generated documentation: https://certora-certora-prover-documentation--326.com.readthedocs.build/en/326/docs/prover/changelog/gui_changelog.html#jan-9-2025
> Uri/rule report changelog 7.22.1

- docs/solana/installation.md
- docs/solana/installation.rst
- docs/solana/scripts/certora_build.py
- docs/solana/scripts/justfile
- docs/solana/usage.md
> solana installation and usage

- docs/prover/approx/hashing.md
- docs/prover/cli/options.md
Improves `--optimistic_hashing` CLI option description.
> improves the optimistic_hashing cli option description

- docs/solana/options.md
> Arie comments

- docs/cvl/foundry-integration.md
- docs/prover/cli/options.md
Note this is sitting on top of https://github.com/Certora/Documentation/pull/344 since it references the `--auto_dispatcher` option.
Link to generated documentation: https://certora-certora-prover-documentation--347.com.readthedocs.build/en/347/docs/prover/cli/options.html#project-sanity
> document `--project_sanity` and `--foundry`

- docs/prover/cli/options.md
> CERT-8156: split_rules documentation

- docs/cvl/foundry-integration.md
This PR just updates the current foundry integration for the current release by removing an outdated limitation around the complexity of the call trace and by stating the new `--foundry` flag.
> Foundry Integration Doc Updates

- docs/prover/changelog/prover_changelog.md
- docs/prover/cli/options.md
Cleans up option titles to just be the flag name for nicer looking internal documentation links. Usage appears in separate lines.
> first pass

- docs/prover/cli/options.md
Ensure all non-advanced flags follow the same format:
Usage, What does it do?, When to use it?, and Example
Also fix math representation in `--precise_bitwise_ops`
> formatting precise_bitwise_ops

- docs/prover/changelog/prover_changelog.md
- docs/user-guide/out-of-resources/timeout.md
Link to generated documentation: https://certora-certora-prover-documentation--368.com.readthedocs.build/en/368/docs/prover/changelog/prover_changelog.html#mar-13-2025
> release notes for v7.26.0

- docs/cvl/expr.md
Removing the `lastHasThrown` keyword which has no effect in Solidity v0.8.0+ and is almost identical to `lastReverted` in older Solidity versions too.
Link to generated documentation: https://certora-certora-prover-documentation--372.com.readthedocs.build/en/372/docs/cvl/expr.html
> removing lastHasThrown

- docs/solana/output.md
- docs/user-guide/out-of-resources/timeout.md
- spelling_wordlist.txt
This PR updates the existing documentation to take into account that Solana supports the Live Stats panel.
In the `timeout` section I explicitly maked as EVM-specific certain sections.
> Solana Livestats update

- docs/cvl/statements.md
Jira ticket: TODO
Link to generated documentation: https://certora-certora-prover-documentation--382.com.readthedocs.build/en/382/
> Remove static_assert and static_require as they are no longer supported

- docs/prover/cli/options.md
Adding internal label to the flag `--multi_example` - needed for Ranger docs
> added label for the flag --multi_example

- docs/prover/cli/options.md
> Document `--exclude_rule`

- docs/prover/changelog/prover_changelog.md
The released version is 7.29.1 and not 7.29.0. Updating the changelog accordingly.
> changelog version 7.29.0 -> 7.29.1

- docs/cvl/expr.md
- docs/cvl/ghosts.md
- docs/prover/cli/options.md
- spelling_wordlist.txt
Jira ticket: [DOC-406](https://certora.atlassian.net/browse/DOC-406)
Links to generated documentation:
- [Syntax for ghosts](https://certora-certora-prover-documentation--435.com.readthedocs.build/en/435/docs/cvl/ghosts.html#syntax) - added missing a production for "axioms"
- [Links to ghost declaration examples](https://certora-certora-prover-documentation--435.com.readthedocs.build/en/435/docs/cvl/ghosts.html#declaring-ghost-variables) - added a link to an example of a ghost with nested mappings, and updated the existing example links because they were permalinks to files that have moved in the latest examples repo (potentially confusing).
- [Mention sum / usum with link](https://certora-certora-prover-documentation--435.com.readthedocs.build/en/435/docs/cvl/ghosts.html#using-ghost-varia …
> Clarify ghosts.md, DOC-406
